version: '3'

tasks:

  aws:dev:
    cmds:
      - aws sso login  --profile AdministratorAccess-017432918922

  tf:lint:
    dir: build
    cmds:
      - tflint

  tf:docs:
    cmds:
      - terraform-docs build {{.CLI_ARGS}}

  tf:fmt:
    env:
      AWS_PROFILE: AdministratorAccess-017432918922
    cmds:
      - terraform fmt -recursive -diff {{.CLI_ARGS}}

  tf:init:
    dir: build
    env:
      AWS_PROFILE: AdministratorAccess-017432918922
      ENV: main
    cmds:
      - terraform init -backend-config={{ .ROOT_DIR }}/deploy/$ENV/backend-$ENV.conf {{ .CLI_ARGS }}
      - terraform providers lock -platform=darwin_amd64 -platform=linux_amd64
  
  tf:validate:
    dir: build
    env:
      AWS_PROFILE: AdministratorAccess-017432918922
    cmds:
      - terraform validate {{.CLI_ARGS}}
      - task: tf:lint

  tf:plan:
    dir: build
    env:
      AWS_PROFILE: AdministratorAccess-017432918922
    cmds:
      - terraform plan {{.CLI_ARGS}}

  tf:apply:
    dir: build
    env:
      AWS_PROFILE: AdministratorAccess-017432918922
    cmds:
      - terraform apply {{.CLI_ARGS}}

  tf:destroy:
    dir: build
    env:
      AWS_PROFILE: AdministratorAccess-017432918922
    cmds:
      - terraform destroy {{.CLI_ARGS}}

  tf:
    dir: build
    env:
      AWS_PROFILE: AdministratorAccess-017432918922
    cmds:
      - terraform {{.CLI_ARGS}}